extern void rtasm_aaa(nativeblockinfo* nat);
extern void rtasm_aad(nativeblockinfo* nat);
extern void rtasm_aam(nativeblockinfo* nat);
extern void rtasm_aas(nativeblockinfo* nat);
extern void rtasm_adc_rm8_r8(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_adc_rm16_r16(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_adc_rm32_r32(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_adc_r8_rm8(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_adc_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_adc_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_add_rm8_r8(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_add_rm16_r16(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_add_rm32_r32(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_add_r8_rm8(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_add_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_add_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_and_rm8_r8(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_and_rm16_r16(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_and_rm32_r32(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_and_r8_rm8(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_and_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_and_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_arpl_rm16_r16(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_bound_r16_m16x2(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_bound_r32_m32x2(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_bsf_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_bsf_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_bsr_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_bsr_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_bswap_r32(nativeblockinfo* nat, uint3 reg);
extern void rtasm_bt_rm16_r16(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_bt_rm32_r32(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_btc_rm16_r16(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_btc_rm32_r32(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_btr_rm16_r16(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_btr_rm32_r32(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_bts_rm16_r16(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_bts_rm32_r32(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_call_rel16(nativeblockinfo* nat, uint4 offset);
extern void rtasm_call_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_call_rm16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_call_rm32(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_call_ptr16_16(nativeblockinfo* nat, uint4 segment, uint4 offset);
extern void rtasm_call_ptr16_32(nativeblockinfo* nat, uint4 segment, uint5 offset);
extern void rtasm_call_m16_16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_call_m16_32(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_cbw(nativeblockinfo* nat);
extern void rtasm_cwde(nativeblockinfo* nat);
extern void rtasm_clc(nativeblockinfo* nat);
extern void rtasm_cld(nativeblockinfo* nat);
extern void rtasm_cli(nativeblockinfo* nat);
extern void rtasm_clts(nativeblockinfo* nat);
extern void rtasm_cmc(nativeblockinfo* nat);
extern void rtasm_cmova_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmova_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovae_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovae_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovb_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovb_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovbe_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovbe_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovc_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovc_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmove_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmove_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovg_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovg_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovge_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovge_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovl_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovl_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovle_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovle_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovna_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovna_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovnae_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovnae_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovnb_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovnb_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovnbe_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovnbe_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovnc_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovnc_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovne_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovne_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovng_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovng_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovnge_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovnge_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovnl_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovnl_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovnle_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovnle_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovno_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovno_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovnp_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovnp_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovns_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovns_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovnz_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovnz_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovo_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovo_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovp_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovp_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovpe_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovpe_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovpo_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovpo_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovs_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovs_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovz_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmovz_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmp_rm8_r8(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_cmp_rm16_r16(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_cmp_rm32_r32(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_cmp_r8_rm8(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmp_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmp_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_cmpsb(nativeblockinfo* nat);
extern void rtasm_cmpsw(nativeblockinfo* nat);
extern void rtasm_cmpsd(nativeblockinfo* nat);
extern void rtasm_cmpxchg_rm8_r8(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_cmpxchg_rm16_r16(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_cmpxchg_rm32_r32(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_cmpxchg8b_m64(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_cpuid(nativeblockinfo* nat);
extern void rtasm_cwd(nativeblockinfo* nat);
extern void rtasm_cdq(nativeblockinfo* nat);
extern void rtasm_daa(nativeblockinfo* nat);
extern void rtasm_das(nativeblockinfo* nat);
extern void rtasm_dec_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_dec_rm16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_dec_rm32(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_dec_r16(nativeblockinfo* nat, uint3 reg);
extern void rtasm_dec_r32(nativeblockinfo* nat, uint3 reg);
extern void rtasm_div_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_div_rm16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_div_rm32(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_emms(nativeblockinfo* nat);
extern void rtasm_f2xm1(nativeblockinfo* nat);
extern void rtasm_fabs(nativeblockinfo* nat);
extern void rtasm_fadd_m32real(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fadd_m64real(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fadd_st0_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fadd_sti_st0(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_faddp_sti_st0(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_faddp(nativeblockinfo* nat);
extern void rtasm_fiadd_m32int(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fiadd_m16int(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fbld_m80dec(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fbstp_m80bcd(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fchs(nativeblockinfo* nat);
extern void rtasm_fclex(nativeblockinfo* nat);
extern void rtasm_fnclex(nativeblockinfo* nat);
extern void rtasm_fcmovb_st0_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fcmove_st0_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fcmovbe_st0_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fcmovu_st0_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fcmovnb_st0_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fcmovne_st0_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fcmovnbe_st0_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fcmovnu_st0_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fcom_m32real(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fcom_m64real(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fcom_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fcom(nativeblockinfo* nat);
extern void rtasm_fcomp_m32real(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fcomp_m64real(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fcomp_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fcomp(nativeblockinfo* nat);
extern void rtasm_fcompp(nativeblockinfo* nat);
extern void rtasm_fcomi_st_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fcomip_st_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fucomi_st_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fucomip_st_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fcos(nativeblockinfo* nat);
extern void rtasm_fdecstp(nativeblockinfo* nat);
extern void rtasm_fdiv_m32real(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fdiv_m64real(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fdiv_st0_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fdiv_sti_st0(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fdivp_sti_st0(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fdivp(nativeblockinfo* nat);
extern void rtasm_fidiv_m32int(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fidiv_m16int(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fdivr_m32real(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fdivr_m64real(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fdivr_st0_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fdivr_sti_st0(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fdivrp_sti_st0(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fdivrp(nativeblockinfo* nat);
extern void rtasm_fidivr_m32int(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fidivr_m16int(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_ffree_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_ficom_m16int(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_ficom_m32int(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_ficomp_m16int(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_ficomp_m32int(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fild_m16int(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fild_m32int(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fild_m64int(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fincstp(nativeblockinfo* nat);
extern void rtasm_finit(nativeblockinfo* nat);
extern void rtasm_fninit(nativeblockinfo* nat);
extern void rtasm_fist_m16int(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fist_m32int(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fistp_m16int(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fistp_m32int(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fistp_m64int(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fld_m32real(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fld_m64real(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fld_m80real(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fld_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fld1(nativeblockinfo* nat);
extern void rtasm_fldl2t(nativeblockinfo* nat);
extern void rtasm_fldl2e(nativeblockinfo* nat);
extern void rtasm_fldpi(nativeblockinfo* nat);
extern void rtasm_fldlg2(nativeblockinfo* nat);
extern void rtasm_fldln2(nativeblockinfo* nat);
extern void rtasm_fldz(nativeblockinfo* nat);
extern void rtasm_fldcw_m2byte(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fldenv_m1428byte(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fmul_m32real(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fmul_m64real(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fmul_st0_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fmul_sti_st0(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fmulp_sti_st0(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fmulp(nativeblockinfo* nat);
extern void rtasm_fimul_m32int(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fimul_m16int(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fnop(nativeblockinfo* nat);
extern void rtasm_fpatan(nativeblockinfo* nat);
extern void rtasm_fprem(nativeblockinfo* nat);
extern void rtasm_fprem1(nativeblockinfo* nat);
extern void rtasm_frndint(nativeblockinfo* nat);
extern void rtasm_frstor_m94108byte(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fsave_m94108byte(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fnsave_m94108byte(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fscale(nativeblockinfo* nat);
extern void rtasm_fsin(nativeblockinfo* nat);
extern void rtasm_fsincos(nativeblockinfo* nat);
extern void rtasm_fsqrt(nativeblockinfo* nat);
extern void rtasm_fst_m32real(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fst_m64real(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fst_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fstp_m32real(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fstp_m64real(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fstp_m80real(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fstp_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fstcw_m2byte(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fnstcw_m2byte(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fstenv_m1428byte(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fnstenv_m1428byte(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fstsw_m2byte(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fstsw_ax(nativeblockinfo* nat);
extern void rtasm_fnstsw_m2byte(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fnstsw_ax(nativeblockinfo* nat);
extern void rtasm_fsub_m32real(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fsub_m64real(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fsub_st0_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fsub_sti_st0(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fsubp_sti_st0(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fsubp(nativeblockinfo* nat);
extern void rtasm_fisub_m32int(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fisub_m16int(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fsubr_m32real(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fsubr_m64real(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fsubr_st0_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fsubr_sti_st0(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fsubrp_sti_st0(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fsubrp(nativeblockinfo* nat);
extern void rtasm_fisubr_m32int(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fisubr_m16int(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_ftst(nativeblockinfo* nat);
extern void rtasm_fucom_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fucom(nativeblockinfo* nat);
extern void rtasm_fucomp_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fucomp(nativeblockinfo* nat);
extern void rtasm_fucompp(nativeblockinfo* nat);
extern void rtasm_fxam(nativeblockinfo* nat);
extern void rtasm_fxch_sti(nativeblockinfo* nat, uint3 stackn);
extern void rtasm_fxch(nativeblockinfo* nat);
extern void rtasm_fxrstor_m512byte(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fxsave_m512byte(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_fxtract(nativeblockinfo* nat);
extern void rtasm_fyl2x(nativeblockinfo* nat);
extern void rtasm_fyl2xp1(nativeblockinfo* nat);
extern void rtasm_hlt(nativeblockinfo* nat);
extern void rtasm_idiv_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_idiv_rm16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_idiv_rm32(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_imul_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_imul_rm16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_imul_rm32(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_imul_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_imul_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_in_al_dx(nativeblockinfo* nat);
extern void rtasm_in_ax_dx(nativeblockinfo* nat);
extern void rtasm_in_eax_dx(nativeblockinfo* nat);
extern void rtasm_inc_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_inc_rm16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_inc_rm32(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_inc_r16(nativeblockinfo* nat, uint3 reg);
extern void rtasm_inc_r32(nativeblockinfo* nat, uint3 reg);
extern void rtasm_ins_m8_dx(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_ins_m16_dx(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_ins_m32_dx(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_insb(nativeblockinfo* nat);
extern void rtasm_insw(nativeblockinfo* nat);
extern void rtasm_insd(nativeblockinfo* nat);
extern void rtasm_int_3(nativeblockinfo* nat);
extern void rtasm_into(nativeblockinfo* nat);
extern void rtasm_invd(nativeblockinfo* nat);
extern void rtasm_invlpg_m(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_iret(nativeblockinfo* nat);
extern void rtasm_iretd(nativeblockinfo* nat);
extern void rtasm_ja_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jae_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jb_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jbe_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jc_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jcxz_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jecxz_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_je_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jg_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jge_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jl_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jle_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jna_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jnae_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jnb_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jnbe_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jnc_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jne_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jng_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jnge_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jnl_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jnle_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jno_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jnp_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jns_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jnz_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jo_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jp_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jpe_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jpo_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_js_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jz_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_ja_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jae_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jb_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jbe_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jc_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_je_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jg_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jge_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jl_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jle_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jna_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jnae_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jnb_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jnbe_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jnc_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jne_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jng_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jnge_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jnl_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jnle_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jno_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jnp_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jns_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jnz_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jo_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jp_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jpe_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jpo_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_js_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jz_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jmp_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_jmp_rel16(nativeblockinfo* nat, uint4 offset);
extern void rtasm_jmp_rel32(nativeblockinfo* nat, uint5 offset);
extern void rtasm_jmp_rm16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_jmp_rm32(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_jmp_ptr16_16(nativeblockinfo* nat, uint4 segment, uint4 offset);
extern void rtasm_jmp_ptr16_32(nativeblockinfo* nat, uint4 segment, uint5 offset);
extern void rtasm_jmp_m16_16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_jmp_m16_32(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_lahf(nativeblockinfo* nat);
extern void rtasm_lar_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_lar_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_ldmxcsr_m32(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_lds_r16_m16_16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_lds_r32_m16_32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_lss_r16_m16_16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_lss_r32_m16_32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_les_r16_m16_16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_les_r32_m16_32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_lfs_r16_m16_16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_lfs_r32_m16_32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_lgs_r16_m16_16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_lgs_r32_m16_32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_lea_r16_m(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_lea_r32_m(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_leave(nativeblockinfo* nat);
extern void rtasm_lgdt_m16n32(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_lidt_m16n32(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_lldt_rm16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_lmsw_rm16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_lock(nativeblockinfo* nat);
extern void rtasm_lods_m8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_lods_m16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_lods_m32(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_lodsb(nativeblockinfo* nat);
extern void rtasm_lodsw(nativeblockinfo* nat);
extern void rtasm_lodsd(nativeblockinfo* nat);
extern void rtasm_loop_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_loope_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_loopz_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_loopne_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_loopnz_rel8(nativeblockinfo* nat, uint3 offset);
extern void rtasm_lsl_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_lsl_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_ltr_rm16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_mov_rm8_r8(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_mov_rm16_r16(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_mov_rm32_r32(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_mov_r8_rm8(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_mov_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_mov_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_mov_rm16_Sreg(nativeblockinfo* nat, rtasm_mtype* mem, uint5 reg);
extern void rtasm_mov_Sreg_rm16(nativeblockinfo* nat, uint5 reg, rtasm_mtype* mem);
extern void rtasm_mov_al_moffs8(nativeblockinfo* nat);
extern void rtasm_mov_ax_moffs16(nativeblockinfo* nat);
extern void rtasm_mov_eax_moffs32(nativeblockinfo* nat);
extern void rtasm_mov_moffs8_al(nativeblockinfo* nat);
extern void rtasm_mov_moffs16_ax(nativeblockinfo* nat);
extern void rtasm_mov_moffs32_eax(nativeblockinfo* nat);
extern void rtasm_mov_cr0_r32(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_mov_cr2_r32(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_mov_cr3_r32(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_mov_cr4_r32(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_mov_r32_cr0(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_mov_r32_cr2(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_mov_r32_cr3(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_mov_r32_cr4(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_mov_r32_dbg(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_mov_dbg_r32(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_movsb(nativeblockinfo* nat);
extern void rtasm_movsw(nativeblockinfo* nat);
extern void rtasm_movsd(nativeblockinfo* nat);
extern void rtasm_movsx_r16_rm8(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_movsx_r32_rm8(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_movsx_r32_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_movzx_r16_rm8(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_movzx_r32_rm8(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_movzx_r32_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_mul_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_mul_rm16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_mul_rm32(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_neg_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_neg_rm16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_neg_rm32(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_nop(nativeblockinfo* nat);
extern void rtasm_not_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_not_rm16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_not_rm32(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_or_rm8_r8(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_or_rm16_r16(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_or_rm32_r32(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_or_r8_rm8(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_or_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_or_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_out_dx_al(nativeblockinfo* nat);
extern void rtasm_out_dx_ax(nativeblockinfo* nat);
extern void rtasm_out_dx_eax(nativeblockinfo* nat);
extern void rtasm_outs_dx_m8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_outs_dx_m16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_outs_dx_m32(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_outsb(nativeblockinfo* nat);
extern void rtasm_outsw(nativeblockinfo* nat);
extern void rtasm_outsd(nativeblockinfo* nat);
extern void rtasm_pop_m16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_pop_m32(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_pop_r16(nativeblockinfo* nat, uint3 reg);
extern void rtasm_pop_r32(nativeblockinfo* nat, uint3 reg);
extern void rtasm_pop_ds(nativeblockinfo* nat);
extern void rtasm_pop_es(nativeblockinfo* nat);
extern void rtasm_pop_ss(nativeblockinfo* nat);
extern void rtasm_pop_fs(nativeblockinfo* nat);
extern void rtasm_pop_gs(nativeblockinfo* nat);
extern void rtasm_popa(nativeblockinfo* nat);
extern void rtasm_popad(nativeblockinfo* nat);
extern void rtasm_popf(nativeblockinfo* nat);
extern void rtasm_popfd(nativeblockinfo* nat);
extern void rtasm_prefetcht0_m8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_prefetcht1_m8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_prefetcht2_m8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_prefetchnta_m8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_push_rm16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_push_rm32(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_push_r16(nativeblockinfo* nat, uint3 reg);
extern void rtasm_push_r32(nativeblockinfo* nat, uint3 reg);
extern void rtasm_push_cs(nativeblockinfo* nat);
extern void rtasm_push_ss(nativeblockinfo* nat);
extern void rtasm_push_ds(nativeblockinfo* nat);
extern void rtasm_push_es(nativeblockinfo* nat);
extern void rtasm_push_fs(nativeblockinfo* nat);
extern void rtasm_push_gs(nativeblockinfo* nat);
extern void rtasm_pusha(nativeblockinfo* nat);
extern void rtasm_pushad(nativeblockinfo* nat);
extern void rtasm_pushf(nativeblockinfo* nat);
extern void rtasm_pushfd(nativeblockinfo* nat);
extern void rtasm_rcl_rm8_1(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_rcl_rm8_cl(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_rcl_rm16_1(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_rcl_rm16_cl(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_rcl_rm32_1(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_rcl_rm32_cl(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_rcr_rm8_1(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_rcr_rm8_cl(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_rcr_rm16_1(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_rcr_rm16_cl(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_rcr_rm32_1(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_rcr_rm32_cl(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_rol_rm8_1(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_rol_rm8_cl(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_rol_rm16_1(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_rol_rm16_cl(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_rol_rm32_1(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_rol_rm32_cl(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_ror_rm8_1(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_ror_rm8_cl(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_ror_rm16_1(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_ror_rm16_cl(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_ror_rm32_1(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_ror_rm32_cl(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_rdmsr(nativeblockinfo* nat);
extern void rtasm_rdpmc(nativeblockinfo* nat);
extern void rtasm_rdtsc(nativeblockinfo* nat);
extern void rtasm_ret(nativeblockinfo* nat);
extern void rtasm_retf(nativeblockinfo* nat);
extern void rtasm_rsm(nativeblockinfo* nat);
extern void rtasm_sal_rm8_1(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_sal_rm8_cl(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_sal_rm16_1(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_sal_rm16_cl(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_sal_rm32_1(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_sal_rm32_cl(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_sar_rm8_1(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_sar_rm8_cl(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_sar_rm16_1(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_sar_rm16_cl(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_sar_rm32_1(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_sar_rm32_cl(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_shl_rm8_1(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_shl_rm8_cl(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_shl_rm16_1(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_shl_rm16_cl(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_shl_rm32_1(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_shl_rm32_cl(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_shr_rm8_1(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_shr_rm8_cl(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_shr_rm16_1(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_shr_rm16_cl(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_shr_rm32_1(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_shr_rm32_cl(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_sbb_rm8_r8(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_sbb_rm16_r16(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_sbb_rm32_r32(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_sbb_r8_rm8(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_sbb_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_sbb_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_scas_m8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_scas_m16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_scas_m32(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_scasb(nativeblockinfo* nat);
extern void rtasm_scasw(nativeblockinfo* nat);
extern void rtasm_scasd(nativeblockinfo* nat);
extern void rtasm_seta_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_setae_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_setb_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_setbe_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_setc_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_sete_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_setg_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_setge_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_setl_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_setle_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_setna_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_setnae_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_setnb_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_setnbe_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_setnc_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_setne_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_setng_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_setnge_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_setnl_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_setnle_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_setno_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_setnp_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_setns_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_setnz_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_seto_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_setp_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_setpe_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_setpo_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_sets_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_setz_rm8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_sfence(nativeblockinfo* nat);
extern void rtasm_sgdt_m(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_sidt_m(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_shld_rm16_r16_cl(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_shld_rm32_r32_cl(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_shrd_rm16_r16_cl(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_shrd_rm32_r32_cl(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_sldt_rm16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_sldt_rm32(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_smsw_rm16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_smsw_r32m16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_stc(nativeblockinfo* nat);
extern void rtasm_std(nativeblockinfo* nat);
extern void rtasm_sti(nativeblockinfo* nat);
extern void rtasm_stmxcsr_m32(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_stos_m8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_stos_m16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_stos_m32(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_stosb(nativeblockinfo* nat);
extern void rtasm_stosw(nativeblockinfo* nat);
extern void rtasm_stosd(nativeblockinfo* nat);
extern void rtasm_str_rm16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_sub_rm8_r8(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_sub_rm16_r16(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_sub_rm32_r32(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_sub_r8_rm8(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_sub_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_sub_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_sysenter(nativeblockinfo* nat);
extern void rtasm_sysexit(nativeblockinfo* nat);
extern void rtasm_test_rm8_r8(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_test_rm16_r16(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_test_rm32_r32(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_ud2(nativeblockinfo* nat);
extern void rtasm_verr_rm16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_verw_rm16(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_wait(nativeblockinfo* nat);
extern void rtasm_fwait(nativeblockinfo* nat);
extern void rtasm_wbinvd(nativeblockinfo* nat);
extern void rtasm_wrmsr(nativeblockinfo* nat);
extern void rtasm_xadd_rm8_r8(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_xadd_rm16_r16(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_xadd_rm32_r32(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_xchg_ax_r16(nativeblockinfo* nat, uint3 reg);
extern void rtasm_xchg_r16_ax(nativeblockinfo* nat, uint3 reg);
extern void rtasm_xchg_eax_r32(nativeblockinfo* nat, uint3 reg);
extern void rtasm_xchg_r32_eax(nativeblockinfo* nat, uint3 reg);
extern void rtasm_xchg_rm8_r8(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_xchg_r8_rm8(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_xchg_rm16_r16(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_xchg_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_xchg_rm32_r32(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_xchg_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_xlat_m8(nativeblockinfo* nat, rtasm_mtype* mem);
extern void rtasm_xor_rm8_r8(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_xor_rm16_r16(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_xor_rm32_r32(nativeblockinfo* nat, rtasm_mtype* mem, uint3 reg);
extern void rtasm_xor_r8_rm8(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_xor_r16_rm16(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
extern void rtasm_xor_r32_rm32(nativeblockinfo* nat, uint3 reg, rtasm_mtype* mem);
