#! /bin/bash
echo "#ifndef ASM86_ALU_H"
echo "#define ASM86_ALU_H 1"
echo
echo "typedef uint5 (asmalufn*)(uint5, uint5, uint5, uint5*);"
echo
for x in `objdump --syms foo.o | grep g*F | colrm 1 33`
do echo "extern uint5 $x(uint5, uint5, uint5, uint5*);"
done
echo
echo "extern asmalufn asmalutab[];"
echo
echo "#endif"
